name: jvm-binary
version: '0.14.0'
author: Christian Gram Kalhauge
maintainer: Christian Gram Kalhauge <kalhauge@cs.ucla.edu>
synopsis: A library for reading Java class-files

license: MIT
license-file: LICENSE.md
category: Language, Java, JVM
github: ucla-pls/jvm-binary

description: A library for reading Java class-files.

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- README.md

dependencies:
- base >= 4.9 && < 4.18
- binary
- bytestring
- containers
- text
- vector
- deepseq >= 1.4.3.0
- deriving-compat
- attoparsec
- mtl
- data-binary-ieee754
- template-haskell

data-files:
  - test/data/project/*

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  jvm-binary-test:
    dependencies:
    - jvm-binary
    - QuickCheck
    - directory
    - filepath
    - generic-random
    - hspec >= 2.5.5
    - hspec-discover
    - hspec-expectations-pretty-diff
    - doctest
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fno-warn-orphans
    main: Main.hs
    source-dirs: test

benchmarks:
  jvm-binary-benchmarks:
    dependencies:
    - jvm-binary
    - criterion
    ghc-options:
    - -rtsopts
    - -O2
    - -threaded
    - -funbox-strict-fields
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
